version: "3"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_value:/var/lib/postgresql/data/

  backend:
    image: kvadimas/portal_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - my_static_value:/app/my_static/
      - media_value:/app/media/
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    container_name: portal

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - static_value:/var/html/static/
      - my_static_value:/var/html/static/my_static/
      - media_value:/var/html/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value:
  my_static_value: