version: "3"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_value:/var/lib/postgresql/data/

  backend:
    build:
      context: .
    restart: always
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    container_name: portal

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - static_value:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  db_value:
  static_value: