version: "3"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_value:/var/lib/postgresql/data/

  couchdb:
    image: couchdb:3
    container_name: db_obsidian
    env_file:
      - .env
    volumes:
      - db_obsidian:/opt/couchdb/data
      - ./CouchDB/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: always

  siribot:
    image: kvadimas/siribot:latest
    restart: always
    ports:
      - 9005:9005
    depends_on:
      - couchdb
    volumes:
      - ./siribot/logging_config.yaml:/app/logging_config.yaml
      - ./siribot/settings.yml:/app/settings.yml

  backend:
    image: kvadimas/portal_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - my_static_value:/app/my_static/
      - media_value:/app/media/
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    container_name: portal

  ml_promobot:
    image: kvadimas/promobot:latest
    restart: always
    env_file: .env
    expose:
      - "9000:9000"
    container_name: ml_promobot

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./pgAdmin4/config_local.py:/pgadmin4/config_local.py
      - pgadmin4_value:/var/lib/pgadmin/
    depends_on:
      - db

  remark42:
    image: umputun/remark42:latest
    restart: always
    container_name: remark42
    env_file:
      - .env
    volumes:
      - comment_value:/srv/var
    depends_on:
      - backend

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - static_value:/var/html/static/
      - my_static_value:/var/html/static/my_static/
      - media_value:/var/html/media/
      - comment_value:/var
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/kvadimas.ru/kvadimas.crt:/etc/ssl/kvadimas.ru.crt:ro
      - /etc/ssl/kvadimas.ru/kvadimas.key:/etc/ssl/kvadimas.ru.key:ro
      - ./robots.txt:/var/html/robots.txt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - ml_promobot

volumes:
  db_value:
  static_value:
  media_value:
  my_static_value:
  comment_value:
  db_obsidian:
  pgadmin4_value: