version: "3"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_value:/var/lib/postgresql/data/

  couchdb:
    image: couchdb:3
    container_name: db_obsidian
    env_file:
      - .env
    volumes:
      - db_obsidian:/opt/couchdb/data
      - ./CouchDB/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - 5984:5984
    restart: always

  backend:
    image: kvadimas/portal_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - my_static_value:/app/my_static/
      - media_value:/app/media/
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    container_name: portal

  remark42:
    image: umputun/remark42:latest
    restart: always
    container_name: remark42
    env_file:
      - .env
    volumes:
      - comment_value:/srv/var
    depends_on:
      - backend

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - static_value:/var/html/static/
      - my_static_value:/var/html/static/my_static/
      - media_value:/var/html/media/
      - comment_value:/var
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/kvadimas.ru/kvadimas.crt:/etc/ssl/kvadimas.ru.crt:ro
      - /etc/ssl/kvadimas.ru/kvadimas.key:/etc/ssl/kvadimas.ru.key:ro
      - ./robots.txt:/var/html/robots.txt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value:
  my_static_value:
  comment_value:
  db_obsidian: