version: "3"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_value:/var/lib/postgresql/data/

  backend:
    build:
      context: .
    restart: always
    command: gunicorn portal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_value:/app/static/
      - my_static_value:/app/my_static/
      - media_value:/app/media/
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    container_name: portal

  remark42:
    image: umputun/remark42:latest
    restart: always
    container_name: remark42
    env_file:
      - .env
    volumes:
      - comment_value:/srv/var
    depends_on:
      - backend

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/
      - my_static_value:/var/html/static/my_static/
      - comment_value:/var
      - media_value:/var/html/media/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  db_value:
  static_value:
  media_value:
  my_static_value:
  comment_value: