# Generated by Django 4.2.5 on 2023-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/images/", verbose_name="Аватарка"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="karma",
            field=models.IntegerField(default=0, verbose_name="Карма"),
        ),
    ]
