# Generated by Django 4.2.6 on 2023-10-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.SlugField(max_length=100, verbose_name="Url"),
        ),
    ]
