# Generated by Django 4.2.6 on 2023-11-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="posting",
            field=models.BooleanField(
                default=False, verbose_name="Публикация на сайте"
            ),
        ),
    ]
