# Generated by Django 4.2.5 on 2023-10-24 22:55

from django.db import migrations
import martor.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_teg_posttag_tag_tag_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=martor.models.MartorField(
                blank=True, max_length=600, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=martor.models.MartorField(verbose_name="Текст"),
        ),
    ]
