# Generated by Django 4.2.6 on 2023-12-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_posting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jpg_png",
                    models.ImageField(
                        upload_to="blog/images/",
                        verbose_name="Ссылка на картинку jpg/png",
                    ),
                ),
                (
                    "webp",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/images/",
                        verbose_name="Ссылка на картинку webp",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        max_length=50, verbose_name="Текстовое описание изображения"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Всплывающая подсказка при наведении курсора",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/images/",
                verbose_name="Ссылка на заглавную картинку на сайте",
            ),
        ),
    ]
