# Generated by Django 4.2.6 on 2023-12-11 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_images_techpost_delete_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="techpost",
            options={
                "verbose_name": "Стабильная статья",
                "verbose_name_plural": "Стабильные статьи",
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
