# Generated by Django 4.2.6 on 2023-12-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_techpost_options_remove_post_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name": "Картинка", "verbose_name_plural": "Картинки"},
        ),
        migrations.AddField(
            model_name="post",
            name="label",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/images/",
                verbose_name="Ссылка на заглавную картинку на сайте",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True, max_length=600, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(verbose_name="Текст"),
        ),
    ]
